In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, yfinance as yf

Matplotlib is building the font cache; this may take a moment.

In [2]:
tickers = ["SPY", "QQQ", "EFA", "EEM", "TLT", "IEF", "LQD", "GLD", "VNQ", "DBC"]
start = "2016-09-01"
end = "2026-09-01"

In [3]:
prices = yf.download(tickers, start=start, end=end)

[*********************100%***********************]  10 of 10 completed

2 Failed downloads:
['EFA', 'LQD']: OperationalError('database is locked')

In [4]:
prices = yf.download(tickers, start=start, end=end, threads=False)

[*********************100%***********************]  10 of 10 completed

In [5]:
prices.head()

Price           Close                                                          \
Ticker            DBC        EEM        EFA         GLD        IEF        LQD
Date
2016-09-01  12.030577  29.565416  43.757145  125.290001  88.417900  86.618980
2016-09-02  12.165847  30.047335  44.263611  126.570000  88.188515  86.464752
2016-09-06  12.250391  30.689880  44.561535  128.710007  88.599800  86.766167
2016-09-07  12.360298  30.593504  44.583881  128.270004  88.647232  86.647011
2016-09-08  12.580112  30.513187  44.457260  127.589996  88.212227  86.037155

Price                                                      ...   Volume  \
Ticker             QQQ         SPY         TLT        VNQ  ...      DBC
Date                                                       ...
2016-09-01  108.934364  184.717041  105.115326  59.699818  ...  2227000
2016-09-02  109.288956  185.549667  104.257965  60.217758  ...  3184400
2016-09-06  109.970139  186.110519  105.017586  60.681923  ...  1680200
2016-09-07  110.035477  186.093506  104.942375  61.045151  ...  1148500
2016-09-08  109.391609  185.668625  103.626259  60.298496  ...  2248200

Price                                                                   \
Ticker            EEM       EFA       GLD      IEF       LQD       QQQ
Date
2016-09-01   67120400  18389800  12877700  1775900  10146300  20944700
2016-09-02   88393000  19151600  11318600  1550100   4155700  18088200
2016-09-06  108573800  14730600  15115300  1284000   6387400  18525200
2016-09-07   58618800  17917500   8859800   836800   2983400  17546900
2016-09-08   73367300  15572700  10561800  1287300   4632300  20125300

Price
Ticker           SPY       TLT      VNQ
Date
2016-09-01  97844200   9149100  4098000
2016-09-02  79293900   8397000  4439500
2016-09-06  56702100   8542600  3874300
2016-09-07  76554900   5421800  2874200
2016-09-08  74102900  14301500  3123900

[5 rows x 50 columns]

In [7]:
prices.shape

(2512, 50)

In [8]:
prices.columns

MultiIndex([( 'Close', 'DBC'),
            ( 'Close', 'EEM'),
            ( 'Close', 'EFA'),
            ( 'Close', 'GLD'),
            ( 'Close', 'IEF'),
            ( 'Close', 'LQD'),
            ( 'Close', 'QQQ'),
            ( 'Close', 'SPY'),
            ( 'Close', 'TLT'),
            ( 'Close', 'VNQ'),
            (  'High', 'DBC'),
            (  'High', 'EEM'),
            (  'High', 'EFA'),
            (  'High', 'GLD'),
            (  'High', 'IEF'),
            (  'High', 'LQD'),
            (  'High', 'QQQ'),
            (  'High', 'SPY'),
            (  'High', 'TLT'),
            (  'High', 'VNQ'),
            (   'Low', 'DBC'),
            (   'Low', 'EEM'),
            (   'Low', 'EFA'),
            (   'Low', 'GLD'),
            (   'Low', 'IEF'),
            (   'Low', 'LQD'),
            (   'Low', 'QQQ'),
            (   'Low', 'SPY'),
            (   'Low', 'TLT'),
            (   'Low', 'VNQ'),
            (  'Open', 'DBC'),
            (  'Open', 'EEM'),
            (  'Open', 'EFA'),
            (  'Open', 'GLD'),
            (  'Open', 'IEF'),
            (  'Open', 'LQD'),
            (  'Open', 'QQQ'),
            (  'Open', 'SPY'),
            (  'Open', 'TLT'),
            (  'Open', 'VNQ'),
            ('Volume', 'DBC'),
            ('Volume', 'EEM'),
            ('Volume', 'EFA'),
            ('Volume', 'GLD'),
            ('Volume', 'IEF'),
            ('Volume', 'LQD'),
            ('Volume', 'QQQ'),
            ('Volume', 'SPY'),
            ('Volume', 'TLT'),
            ('Volume', 'VNQ')],
           names=['Price', 'Ticker'])

In [9]:
close = prices["Close"]

In [10]:
close.head()

Ticker,DBC,EEM,EFA,GLD,IEF,LQD,QQQ,SPY,TLT,VNQ
Date,,,,,,,,,,
2016-09-01,12.030577,29.565416,43.757145,125.290001,88.417900,86.618980,108.934364,184.717041,105.115326,59.699818
2016-09-02,12.165847,30.047335,44.263611,126.570000,88.188515,86.464752,109.288956,185.549667,104.257965,60.217758
2016-09-06,12.250391,30.689880,44.561535,128.710007,88.599800,86.766167,109.970139,186.110519,105.017586,60.681923
2016-09-07,12.360298,30.593504,44.583881,128.270004,88.647232,86.647011,110.035477,186.093506,104.942375,61.045151
2016-09-08,12.580112,30.513187,44.457260,127.589996,88.212227,86.037155,109.391609,185.668625,103.626259,60.298496